### ISSUE TITLE
Compilation error on ESP8266WM_Config.ino example

### ISSUE THREAD

**Issue by mikekgr** [khoih-prog/Blynk_WM#1]
Dear Mr. Khoih
I tried in my Arduino, your following example:
https://github.com/khoih-prog/Blynk_WM/blob/master/examples/ESP8266WM_Config/ESP8266WM_Config.ino

Unfortunatelly I got compilation error as you can see
In file included from E:\ARDUINO_ESP_DEV\arduino-IDE\portable\sketchbook\libraries\Blynk_WiFiManager\examples\ESP8266WM_Config\ESP8266WM_Config.ino:53:0:

E:\ARDUINO_ESP_DEV\arduino-IDE\portable\sketchbook\libraries\Blynk_WiFiManager\src/BlynkSimpleEsp8266_SSL_WM.h:51:36: fatal error: certs/blynkcloud_der.h: No such file or directory

   #include <certs/blynkcloud_der.h>

                                    ^
compilation terminated.

Do you know why? did i do something wrong?

Thanks and Best Regards,
Mike Kranidis

**Comment by khoih-prog** [comment]
Hello Mike,
Thanks for testing this library. Hope you have a wonderful New Year 2020.

RE: The compiling error:

I think you are using the example with `SSL` option.

1. If you're not using SSL, please just change this line in the example's code from

```
#define USE_SSL   true
```
to 

```
#define USE_SSL   false
```
2. If you're using `SSL`, with `Blynk Cloud Server`, please 

- Move the file BlynkSimpleEsp8266_SSL_WM.h (for ESP8266),  and BlynkSimpleEsp32_SSL_WM.h (for ESP32) to Blynk libraries src directory (normally ./Arduino/libraries/Blynk/src)

3. If you're using SSL with Local Blynk Server, there are many more steps you have to do to make your Local Blynk Server working with SSL. Please inform if you're interested in this option.

Best Regards,

KH

**Comment by mikekgr** [comment]
> Hello Mike,
> Thanks for testing this library. Hope you have a wonderful New Year 2020.
> 
> RE: The compiling error:
> 
> I think you are using the example with `SSL` option.
> 
> 1. If you're not using SSL, please just change this line in the example's code from
> 
> ```
> #define USE_SSL   true
> ```
> 
> to
> 
> ```
> #define USE_SSL   false
> ```
> 
> 1. If you're using `SSL`, with `Blynk Cloud Server`, please
> 
> * Move the file BlynkSimpleEsp8266_SSL_WM.h (for ESP8266),  and BlynkSimpleEsp32_SSL_WM.h (for ESP32) to Blynk libraries src directory (normally ./Arduino/libraries/Blynk/src)
> 
> 1. If you're using SSL with Local Blynk Server, there are many more steps you have to do to make your Local Blynk Server working with SSL. Please inform if you're interested in this option.
> 
> Best Regards,
> 
> KH

Dear Mr. Khoih,
thanks a lot for your kind wishes, let me wish to you for a healthy happy and prosperous New year!

Regarding your proposed solution, I will try it later or tomorrowand I will let you know.

Many thanks for your support and your lovely work and contribution to the community.

Best Regards,
Mike Kranidis

**Comment by mikekgr** [comment]
> Hello Mike,
> Thanks for testing this library. Hope you have a wonderful New Year 2020.
> 
> RE: The compiling error:
> 
> I think you are using the example with `SSL` option.
> 
> 1. If you're not using SSL, please just change this line in the example's code from
> 
> ```
> #define USE_SSL   true
> ```
> 
> to
> 
> ```
> #define USE_SSL   false
> ```
> 
> 1. If you're using `SSL`, with `Blynk Cloud Server`, please
> 
> * Move the file BlynkSimpleEsp8266_SSL_WM.h (for ESP8266),  and BlynkSimpleEsp32_SSL_WM.h (for ESP32) to Blynk libraries src directory (normally ./Arduino/libraries/Blynk/src)
> 
> 1. If you're using SSL with Local Blynk Server, there are many more steps you have to do to make your Local Blynk Server working with SSL. Please inform if you're interested in this option.
> 
> Best Regards,
> 
> KH

Dear Mr. Khoih,
I can confirm that using the #define USE_SSL   false as you suggested, compiled fine.
Perhaps you should have this as default.

Thanks and Best Regards,
Mike Kranidis

P.S. You can close the issue now

**Comment by khoih-prog** [comment]
Dear Mike,
Already change to default

```
#define USE_SSL   false
```
and close the issue.

Best Regards,
KH
