### ISSUE TITLE
Changing settings in example sketch doesn't reflect on device

### ISSUE THREAD

**Issue by ghost** [khoih-prog/Blynk_WM#14]
Using Wemos D1 Mini.

1. Installed new copy of Arudino on new computer
2. Installed libraries blynk, DHT, blynkWM, and all libraries indicated as dependant.
3. Loaded default sketch DHT11ESP8266
4. in main sketch ino file changed Blynk.setConfigPortal("TestPortal", "TestPortalPass");  to    Blynk.setConfigPortal("Test", "test"); but SSID doesn't show new SSID name for config portal.

Notes:
- Changing Blynk.setConfigPortalIP(IPAddress(192, 168, 200, 1)); to new IP worked
- tried making changes to some other settings, they didn't reflect either:

**Comment by khoih-prog** [comment]
You made a mistake in using the WPA2 password length less than 8 chars.

It'll be OK if you're using

```
// WPA2 PW length must be 8+ to be valid
Blynk.setConfigPortal ( "TestPortal", "12345678" );  
```

Have a look at the similar topic in Blynk Forum:

[WM Config Portal using BlynkSimpleEsp32/8266_WM.h](https://community.blynk.cc/t/wm-config-portal-using-blynksimpleesp32-8266-wm-h/45402)

> I have been unable to get the WM Config Portal AP SSID and Password to set, keep getting the default WiFi name and password. (The Config Portal IP Address worked for me, thanks!) Any ideas?

then

> I changed the WiFi password to 8 characters and all is right with the world! I

**Comment by ghost** [comment]
Thank you very much.
