### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by Pippozz** [khoih-prog/Blynk_WM#19]
Hi khoih,
first of all thanks for all the work you put in this project.

I'm implementing your code into a simple blynk sketch but I can't compile.
I checked again the prerequisites but It doesn't seem to work anyway... I'm pretty sure I'm missing something

Those are the errors:
[error.txt](https://github.com/khoih-prog/Blynk_WM/files/4943897/error.txt)

Thanks for the help

**Comment by khoih-prog** [comment]
@Pippozz 

Thanks for using the library.

You have some mismatch between [Blynk_WM Version](https://github.com/khoih-prog/Blynk_WM) and code. The recent versions have drastic changes to support dynamic parameters, and require some more header files. Check [ESP8266WM_Config example](https://github.com/khoih-prog/Blynk_WM/tree/master/examples/ESP8266WM_Config).

Please start with an example of the corresponding version, then modify from that. Going thru [README](https://github.com/khoih-prog/Blynk_WM/blob/master/README.md) will be also helpful.

Good luck.

**Comment by Pippozz** [comment]
Thank you for your reply.
For sure ill give it a shot.

Bye,
Filippo
