### ISSUE TITLE
AP stays open

### ISSUE THREAD

**Issue by chriskio** [khoih-prog/Blynk_WM#2]
Evervthing seems to work fine except the Config mode AP is still on atfer reset along with the connection to my router and server. Sometimes my phone will connect to it instead of my router and nothing will work. I am new to this so apologies if it's something simple i'm doing wrong.

**Comment by khoih-prog** [comment]
Hi @chriskio 

Thanks for using the lib. This is a real bug I'll fix ASAP.
In the mean time, please go to the cellphone to either:
1. Forget 
2. Select "Not Auto-Join`
the unwanted Config Mode AP

Regards,

**Comment by khoih-prog** [comment]
Done. Fixed in v1.0.8 and your contribution is noted.
Regards,
