### ISSUE TITLE
How to trigger a Config Portal from code

### ISSUE THREAD

**Issue by thorathome** [khoih-prog/Blynk_WM#25]
Hi @khoih-prog 
Yes, it's been some while. I'm back at it, adding OTA to all my sketches.  

Request: I have forgotten how to cause the Config Portal to come up from a ESP32 or 8266 sketch. 
I thought `Blynk.clearConfigData(); `followed by a `ESP.restart(); `would do it. The restart works, but the Confog Portal doesn't post. 

Would you be kind enough to (re)explain how to get a Config Portal up besides mechanically using DRD? (I'm going for touch-free devices!)

Thanks again for all your help, and in advance. 
```

{
    // Get the Reset button value, Hit Reset and reboot if = 1
    int buttonVal = param[0].asInt();
    Serial.print ( "     " ); 
    Serial.print ( "RESET Button Hit with value = " ); Serial.println ( buttonVal );  

    if ( buttonVal == 1 )
    {
      Serial.println ( " \n REBOOTING " );  
      Blynk.clearConfigData(); 
      delay ( 8000 );  
      ESP.restart();
    }
}


```
I've been using your Blynk_WM on SONOFFs and on a variety of ESPx monitors. WM Library has been helpful, stable, useful and reliable to me. Thanks.  
@thorathome

**Comment by khoih-prog** [comment]
Hi @thorathome 

You're doing correctly, almost, but this

```
bool LOAD_DEFAULT_CONFIG_DATA = false;
```

When settings 

```
bool LOAD_DEFAULT_CONFIG_DATA = true;
```

the lib will ignore the blank data erased by`Blynk.clearConfigData(); ` and continue as normal.

**Comment by thorathome** [comment]
@khoih-prog Thank you, kind sir, for the instantaneous help. You are correct, of course.  
Easy to forget details. 

I am enjoying the library, working on OTA these days. 
Be well.  Best wishes.  
@thorathome

**Comment by thorathome** [comment]
@khoih-prog Is there a way from code to trigger the Config Portal (for minor changes to field values) without erasing it?

**Comment by khoih-prog** [comment]
In next release, I'll add a function to let you force entering the Config Portal, from code, so that you can use Hardware, Virtual SW or any condition to trigger Config Portal. Certainly better without erasing Config Data.

Be safe there, BR,

KH

**Comment by thorathome** [comment]
And one more, please. I see the ESP8266 and ESP32 are broadcasting their own WiFi signals (with 6-digit numeric SSIDs) while, otherwise, acting as expected. 
Is there an easy way to shut off those signals?

**Comment by khoih-prog** [comment]
> And one more, please. I see the ESP8266 and ESP32 are broadcasting their own WiFi signals (with 6-digit numeric SSIDs) while, otherwise, acting as expected.
> Is there an easy way to shut off those signals?

This tempo SSID will appear is only very shortly, if happens.
I experienced this issue with the **slow ESP8266-AT-command shields** only, and haven't seen on ESP8266/ESP32, at least with the library's examples. I currently haven't met and have no idea yet how to fix.

Check your code to see if and where you call the following functions prematurely, or possibly so much delay() in the code and  interfering with the library WiFi operation ???

```
WiFi.mode(WIFI_AP);
...
WiFi.softAP(portal_ssid.c_str(), portal_pass.c_str(), channel);
...
WiFi.softAPConfig(portal_apIP, portal_apIP, IPAddress(255, 255, 255, 0));
```

**Comment by thorathome** [comment]
Embarrassing for me, I now realize these are the TelNetStream signals I am now using with OTA. All good here. 
Enjoy the rest of your Friday. 

I'll use any new feature you offer which lets me trigger an uncleared ConfigPortal. It would be a useful capability. 

Thanks again @khoih-prog Much appreciated.  
@thorathome

**Comment by khoih-prog** [comment]
Will release with several days. You're very welcome as every time you talk, we'll have new ideas and release.

**Comment by thorathome** [comment]
Thanks to your work and our collaboration, I now have a small fleet of SONOFF switches and a handful of temperature and barometer sensors. I built an air conditioning automatic control system, and use IFTTT for Google Assistant automation. This is fun when I get time to program. Your libraries work and Blynk works. 

Be well.

**Comment by khoih-prog** [comment]
That's good to know the lib somehow is helpful, keeps you going and having fun. I'm looking forward to using devices with your software some time in the future.

I used to write some software for SONOFF SWs, several years ago for fun, to use in my house lightings, controlled by Blynk, Alexa, etc., and haven't so far touched and modified. Luckily they are still working reliably. So busy with maintaining so many libraries now.

**Comment by khoih-prog** [comment]
I just finished the first mods and tested successfully the lib with the new CP feature. Will release within several days.

The new feature will be

1. Non-persistent forced CP => you can force to enter the CP once, and clear the request even if you haven't changed /saved new info in the CP. After reset (HW or Virtual SW), the normal operation will resume without CP
2. Persistent forced CP => request will be cleared only after CP entered and new data saved. Even reset w/o saving new data, the CP will re-appear until new data saved.
3. I guess you can also use double/multi reset feature with Virtual SW (by pressing the Virtual SW => reset => pressing the Virtual SW again within predetermined time => CP by DRD/MRD. This is currently supported.

**Comment by khoih-prog** [comment]
Please check the new release

---
### Releases v1.1.1

1. Add functions to **control Config Portal (persistent or non-persistent) from software or Virtual Switches**. Check [**How to trigger a Config Portal from code #25**](https://github.com/khoih-prog/Blynk_WM/issues/25)
2. Add examples to demo the new Virtual ConfigPortal SW feature
3. Optimize code

---

and these new examples demonstrating the new features

* [13. **ESP32WM_ForcedConfig**](https://github.com/khoih-prog/Blynk_WM/tree/master/examples/ESP32WM_ForcedConfig)
* [14. **ESP8266WM_ForcedConfig**](https://github.com/khoih-prog/Blynk_WM/tree/master/examples/ESP8266WM_ForcedConfig)
* [15. **ESP32WM_MRD_ForcedConfig**](https://github.com/khoih-prog/Blynk_WM/tree/master/examples/ESP32WM_MRD_ForcedConfig)
* [16. **ESP8266WM_MRD_ForcedConfig**](https://github.com/khoih-prog/Blynk_WM/tree/master/examples/ESP8266WM_MRD_ForcedConfig)

**Comment by khoih-prog** [comment]
This useful feature has been added to [Blynk_Async_WM Library](https://github.com/khoih-prog/Blynk_Async_WM) and will be added to many more Blynk-related libs such as 

- [x] 1. [BlynkEthernet_WM](https://github.com/khoih-prog/BlynkEthernet_WM)
- [x] 2. [BlynkESP32_BT_WF](https://github.com/khoih-prog/BlynkESP32_BT_WF)
- [x] 3. [BlynkEthernet_STM32_WM](https://github.com/khoih-prog/BlynkEthernet_STM32_WM)
- [x] 4. [Blynk_Esp8266AT_WM](https://github.com/khoih-prog/Blynk_Esp8266AT_WM)
- [ ] 5. [Blynk_WiFiNINA_WM](https://github.com/khoih-prog/Blynk_WiFiNINA_WM)
- [x] 6. [BlynkGSM_Manager](https://github.com/khoih-prog/BlynkGSM_Manager)
- [x] 7. [Blynk_Async_GSM_Manager](https://github.com/khoih-prog/Blynk_Async_GSM_Manager)
- [x] 8. [Blynk_Async_ESP32_BT_WF](https://github.com/khoih-prog/Blynk_Async_ESP32_BT_WF)

Every time you introduce a new idea, there are to much work for me, yet make me thinking and enjoying. Thanks.

---

- [x]  [Blynk_Async_WM v1.2.1](https://github.com/khoih-prog/Blynk_Async_WM/releases/tag/v1.2.1)

### Releases v1.2.1

1. Add functions to control Config Portal from software or Virtual Switches. Check [How to trigger a Config Portal from code #25](https://github.com/khoih-prog/Blynk_WM/issues/25)
2. Add examples to demo the new Virtual ConfigPortal SW feature
3. Optimize code
